# Generated by Django 5.2.9 on 2025-12-04 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_parentprofile_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='stream',
            field=models.CharField(blank=True, choices=[('1 WEST', '1 WEST'), ('1 EAST', '1 EAST'), ('1 NORTH', '1 NORTH'), ('1 SOUTH', '1 SOUTH'), ('2 WEST', '2 WEST'), ('2 EAST', '2 EAST'), ('2 NORTH', '2 NORTH'), ('2 SOUTH', '2 SOUTH'), ('3 WEST', '3 WEST'), ('3 EAST', '3 EAST'), ('3 NORTH', '3 NORTH'), ('3 SOUTH', '3 SOUTH'), ('4 WEST', '4 WEST'), ('4 EAST', '4 EAST'), ('4 NORTH', '4 NORTH'), ('4 SOUTH', '4 SOUTH')], max_length=20),
        ),
    ]
