# Generated by Django 5.2.8 on 2025-12-07 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('admission_number', models.CharField(max_length=50, unique=True)),
                ('stream', models.CharField(blank=True, choices=[('1E', 'Form 1 East'), ('1W', 'Form 1 West'), ('1N', 'Form 1 North'), ('1S', 'Form 1 South'), ('2E', 'Form 2 East'), ('2W', 'Form 2 West'), ('2N', 'Form 2 North'), ('2S', 'Form 2 South'), ('3E', 'Form 3 East'), ('3W', 'Form 3 West'), ('3N', 'Form 3 North'), ('3S', 'Form 3 South'), ('4E', 'Form 4 East'), ('4W', 'Form 4 West'), ('4N', 'Form 4 North'), ('4S', 'Form 4 South')], max_length=10)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='students/')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DisciplineReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('cheating', 'Cheating'), ('bullying', 'Bullying'), ('lateness', 'Lateness'), ('disruption', 'Class Disruption')], max_length=50)),
                ('description', models.TextField()),
                ('evidence', models.FileField(blank=True, null=True, upload_to='evidence/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, null=True)),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_cases', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.student')),
            ],
        ),
    ]
