# Generated by Django 5.2.8 on 2025-12-07 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream', models.CharField(blank=True, choices=[('1E', 'Form 1 East'), ('1W', 'Form 1 West'), ('1N', 'Form 1 North'), ('1S', 'Form 1 South'), ('2E', 'Form 2 East'), ('2W', 'Form 2 West'), ('2N', 'Form 2 North'), ('2S', 'Form 2 South'), ('3E', 'Form 3 East'), ('3W', 'Form 3 West'), ('3N', 'Form 3 North'), ('3S', 'Form 3 South'), ('4E', 'Form 4 East'), ('4W', 'Form 4 West'), ('4N', 'Form 4 North'), ('4S', 'Form 4 South')], max_length=10, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
