# Generated by Django 5.2.8 on 2025-12-09 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_teacherprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stream',
            field=models.CharField(blank=True, choices=[('Form 1 East', 'Form 1 East'), ('Form 1 West', 'Form 1 West'), ('Form 1 North', 'Form 1 North'), ('Form 1 South', 'Form 1 South'), ('Form 2 East', 'Form 2 East'), ('Form 2 West', 'Form 2 West'), ('Form 2 North', 'Form 2 North'), ('Form 2 South', 'Form 2 South'), ('Form 3 East', 'Form 3 East'), ('Form 3 West', 'Form 3 West'), ('Form 3 North', 'Form 3 North'), ('Form 3 South', 'Form 3 South'), ('Form 4 East', 'Form 4 East'), ('Form 4 West', 'Form 4 West'), ('Form 4 North', 'Form 4 North'), ('Form 4 South', 'Form 4 South')], max_length=15),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='stream',
            field=models.CharField(blank=True, choices=[('Form 1 East', 'Form 1 East'), ('Form 1 West', 'Form 1 West'), ('Form 1 North', 'Form 1 North'), ('Form 1 South', 'Form 1 South'), ('Form 2 East', 'Form 2 East'), ('Form 2 West', 'Form 2 West'), ('Form 2 North', 'Form 2 North'), ('Form 2 South', 'Form 2 South'), ('Form 3 East', 'Form 3 East'), ('Form 3 West', 'Form 3 West'), ('Form 3 North', 'Form 3 North'), ('Form 3 South', 'Form 3 South'), ('Form 4 East', 'Form 4 East'), ('Form 4 West', 'Form 4 West'), ('Form 4 North', 'Form 4 North'), ('Form 4 South', 'Form 4 South')], max_length=15, null=True),
        ),
    ]
