# Generated by Django 5.2.8 on 2025-12-09 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_student_stream_alter_teacherprofile_stream'),
    ]

    operations = [
    ]
